#!/bin/bash
#sudo apt install gtk2-engines-murrine gtk2-engines-pixbuf subversion

# 安装字体source-code-pro
mkdir -p ~/.fonts/
git clone --depth 1 --branch release https://github.com/adobe-fonts/source-code-pro.git ~/.fonts/source-code-pro
fc-cache -f -v ~/.fonts/source-code-pro

# 安装桌面gtk主题matcha
mkdir -p ~/.local/share/applications/
wget -P ~/.local/share/applications/ https://github.com/vinceliuice/matcha/blob/master/update-matcha-online.desktop
chmod +x ~/.local/share/applications/update-matcha-online.desktop
~/.local/share/applications/update-matcha-online.desktop

# 安装图标主题la-capitaine
mkdir -p ~/.icons/ && cd ~/.icons/
git clone https://github.com/keeferrourke/la-capitaine-icon-theme.git
cd ./la-capitaine-icon-theme/
svn checkout https://github.com/keeferrourke/capitaine-cursors/trunk/dist/cursors
gtk-update-icon-cache ~/.icons/la-capitaine-icon-theme

# xfce4桌面图标下字体阴影解决:
xfconf-query -c xfce4-desktop -p /desktop-icons/center-text -n -t bool -s false
